### ISSUE TITLE
Proposal to drop the timeline property and class

### ISSUE THREAD

**Issue by csarven** [solid/vocab#27]
Proposal to drop solid terms' `timeline` property and `Timeline` class.

Intended semantics and usage overlaps with [https://www.w3.org/TR/activitypub/](https://www.w3.org/TR/activitypub)'s *Outbox*: https://www.w3.org/TR/activitypub/#outbox - which is basically a container/collection of activities. There is also a growing list of applications/servers that implement https://activitypub.rocks/implementation-report/ , hence more likely to work interop with.

In contrast tot as:outbox, solid:timeline for instance is underspecified.

If there is nothing mission critical or great adoption, I suggest favouring/encouraging the use of `as:outbox` instead of `solid:timeline`.

If you are using solid term's timeline in an application, please indicate if it is actively used or still in working condition along with the URL to the application. If you are against the proposal to remove, please indicate if/why `solid:timeline` is preferable to you over `as:outbox`.

**Comment by kidehen** [comment]
@csarven,

Why not simply add the following for now, since that would be less disruptive:
@prefix solid: <https://www.w3.org/ns/solid/terms#> . 
@prefix as: <http://www.w3.org/ns/activitystreams#> . 
solid:timeline owl:equivalentProperty as:outbox . 

BTW -- http://www.w3.org/ns/activitystreams# still doesn't resolve to an RDF document (be it JSON-LD or RDF-Turtle or some other notation).

**Comment by csarven** [comment]
The equivalance relation would be fine but I really wonder if it is worth it. If there is no significant usage, I think it'd be favourable to simply drop it as to not pollute the solid terms ns.

`curl -kHL 'Accept: application/ld+json' http://www.w3.org/ns/activitystreams` works, but AFAICT, it doesn't have other RDF representations (at this time).

**Comment by melvincarvalho** [comment]
Thanks for the suggestion and very valuable pointers.

Currently timeline is used in my social app, named timeline.

Will have a look at as : outbox, when I get some time free, and see if it is a good match for the app.

**Comment by csarven** [comment]
Is the application public? What's the URL? Actively maintained/used?

**Comment by timbl** [comment]
@csarven Remember @melvincarvalho has all kinds of apps and poof of concept things which he keeps on various shelves but may be brought out quickly if they get priority.

I am interested in the timeline problem, as th home pane (currently extremely rudimentary) only lists things and does not put them in order, and I need a timeline personally.   I am thinking of changing the widget which tracks public and private uses of an app and adding timeline output to it. UI.authn.registrationControl  https://github.com/linkeddata/solid-ui/blob/master/src/signin.js#L422  -- the "Keep a private/public note of this xxxx" box in the meetulator for example

**Comment by melvincarvalho** [comment]
@csarven currently 2 URIs for timeline

URIs iirc :
- http://solid-social.github.io/timeline/?date=recent&profile=https:%2F%2Fmelvincarvalho.com%2F%23me 
- https://github.com/solid-social/timeline

There has been some interest in this social app.  It was put on ice for a while due to 
[x] Waiting for OIDC to be coded
[  ] Resource to  code it up
[  ] Angular made breaking changes that require a refactor

I agree that timeline is under specified.  Part of the reason is that we needed to find out how DSN would perform under the solid paradigm.

Do you think AS : outbox is an equivalent property.  It sounds a bit different.  Timeline I consider to be a list of all your posts over time.  Outbox I am familiar with from the email paradigm where you send messages and they are in a container ready to be processed.
