### ISSUE TITLE
Process for replacing vocabulary terms that might be in use

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/vocab#32]
#30 / #31

**Comment by RubenVerborgh** [comment]
Based on #31 / #33 / #34, I propose the following process:

1. Discuss on deprecation (#31)
2. If an agreement is reached, deprecate (#33)
3. Update all of our apps (#34)

**Comment by melvincarvalho** [comment]
A discussion on deprecation that lasts less than a day?   This is how to break the public contract and lose trust in your users.  I could not be possibly more opposed.

And, what about apps not in our repos?

And what about that the predicate exists in our profiles?

This kind of trigger happy unnecessary breakage, creates a tainted brand.  In short, I'm worried.

**Comment by melvincarvalho** [comment]
To mitigate, I would suggest opening the discussion for a longer period.  Stake holders have not had a chance to weigh in.

I would suggest going changing apps to use either predicate, in the event of a deprecation.

**Comment by RubenVerborgh** [comment]
To be fair, that particular discussion was dragging on for years, and only one (valid) opinion was in the way of concensus. So the moment that changed, there was agreement and action.

Do you agree on the process steps? I agree on the necessity of time.

**Comment by melvincarvalho** [comment]
Agreed.  In summary

- Can live with the outcome of this event -- tho disruption was caused due to lack of process

- In future we'll all time for a proper discussion, pull requests and review

- We will use owl : deprecate, rather than deleting for terms in use.  Im hesitant for the "in use" phrase there.  It's a bit like "temporary".  Let's say it's in use if one stake holder (formally) objects.

Thanks for your help.

**Comment by RubenVerborgh** [comment]
Fine with me!

**Comment by kjetilk** [comment]
Sounds good! I'll close.
